spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/invest
    driver-class-name: org.postgresql.Driver
    username: invest
    password: invest

logging:
  level:
    root: INFO
    ru.isg: DEBUG
    org.hibernate.SQL: INFO

pf-man:
  images:
    base:
      path: ./

tinkoff:
  api:
    token:

telegram:
  bot:
    username: Investment Storyteller
    token: