version: '2.4'
services:

  invest-nginx:
    image: nginx:alpine
    container_name: invest-nginx
    hostname: invest-nginx
    restart: unless-stopped
    ports:
      - "50080:80"
    networks:
      - invest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  invest-db:
    image: postgres:14.3-alpine
    container_name: invest-db
    hostname: invest-db
    restart: unless-stopped
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: invest
    networks:
      - invest

  invest-helper:
    image: invest/invest-helper
    container_name: invest-helper
    restart: always
    ports:
      - "58080:8080"
    environment:
      SPRING_CONFIG_NAME: "application"
      SPRING_CONFIG_LOCATION: "file:///config/"
      TELEGRAM_BOT_USERNAME: "${TELEGRAM_BOT_USERNAME}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TINKOFF_API_TOKEN: "${TINKOFF_API_TOKEN}"
    volumes:
      - "./invest-helper/config:/config"
      - "./invest-helper/logs:/logs"
      - "./invest-helper/data:/data"
    networks:
      - invest
    depends_on:
      - invest-db

networks:
  invest:


